Repository oncokb/oncokb-public, pull requests merged in 2019-12, with the labels that each got.

#321 Show PMID links in gene background
  .eslintrc.json
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
  src/main/webapp/app/shared/utils/UrlUtils.tsx
Labels: Ready to review

#324 Redirect to Home Page for 404 error
  src/main/webapp/app/routes/routes.tsx
Labels: do not merge

#352 Support New Levels of Evidence (v2) && Add News Anchor tag
  package.json
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/index.scss
  src/main/webapp/app/pages/LevelOfEvidencePage.tsx
  src/main/webapp/app/pages/genePage/GenePage.module.scss
  src/main/webapp/app/pages/newsPage/NewsList.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/routes/routes.tsx
  src/main/webapp/app/shared/links/HashLink.tsx
  src/main/webapp/app/shared/links/Linkout.tsx
  src/main/webapp/app/shared/utils/Utils.tsx
  src/main/webapp/content/images/loe-change.png
  yarn.lock
Labels: feature
