Repository oncokb/oncokb-public, pull requests merged in 2020-12, with the labels that each got.

#558 Setup Dx/Px instance
  src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java
  src/main/webapp/app/routes/routes.tsx
Labels: feature

#559 Show level column first in the gene/variant page tables
  src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
Labels: enhancement

#556 Show Tx/Dx/Px seperately on Home Page and Actionable Genes Page
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/HomePage.tsx
  src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx
  src/main/webapp/app/pages/actionableGenesPage/LevelSelectionRow.tsx
  src/main/webapp/app/routes/routes.tsx
  src/main/webapp/app/shared/utils/Utils.tsx
Labels: feature

#560 Update OncoTree link
  src/main/webapp/app/components/Footer.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
  src/main/webapp/app/shared/api/generated/OncoKbAPI-docs.json
  src/main/webapp/app/shared/api/generated/OncoKbAPI.ts
  src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI-docs.json
  src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI.ts
Labels: fix

#561 Show Tx/Dx/Px seperately on Home Page and Actionable Genes Page - Stage 2
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/HomePage.tsx
  src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx
  src/main/webapp/app/pages/actionableGenesPage/LevelSelectionRow.tsx
  src/main/webapp/app/shared/utils/Utils.tsx
Labels: enhancement, feature

#550 Send email when token exposed
  pom.xml
  src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java
  src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/MailType.java
  src/main/java/org/mskcc/cbio/oncokb/security/uuid/TokenProvider.java
  src/main/java/org/mskcc/cbio/oncokb/service/MailService.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/ExposedToken.java
  src/main/resources/config/application-dev.yml
  src/main/resources/i18n/messages.properties
  src/main/resources/templates/mail/activationEmail.html
  src/main/resources/templates/mail/approvalEmail.html
  src/main/resources/templates/mail/creationEmail.html
  src/main/resources/templates/mail/licenseReview.html
  src/main/resources/templates/mail/passwordResetEmail.html
  src/main/resources/templates/mail/searchingResponseStructureHasChanged.html
  src/main/resources/templates/mail/tokenHasBeenExposed.html
  src/main/resources/templates/mail/tokenHasBeenExposedToUser.html
Labels: feature

#562 Update OncoKB workflow image in the about page
  src/main/webapp/app/pages/AboutPage.tsx
  src/main/webapp/content/images/process.jpg
  src/main/webapp/content/images/process.png
Labels: fix

#563 Adjust grid layout
  src/main/webapp/app/components/Header.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/store/WindowStore.ts
  src/main/webapp/app/variables.scss
Labels: fix

#564 update genes page and variant page to show Dx/Px
  src/main/webapp/app/pages/alterationPage/AlterationPage.module.scss
  src/main/webapp/app/pages/annotationPage/AlterationInfo.tsx
  src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
  src/main/webapp/app/pages/annotationPage/AnnotationPageTable.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
  src/main/webapp/app/pages/genePage/GenePageTable.tsx
Labels: feature

#567 Add OncoTree Linkout && Change Tumor Type to Cancer Type
  src/main/webapp/app/components/Footer.tsx
  src/main/webapp/app/pages/ActionableGenesPage.tsx
  src/main/webapp/app/pages/HomePage.tsx
  src/main/webapp/app/pages/alterationPage/AlterationPage.tsx
  src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
  src/main/webapp/app/pages/hgvsgPage/HgvsgPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
  src/main/webapp/app/shared/icons/ExternalLinkIcon.tsx
  src/main/webapp/app/shared/utils/UrlUtils.tsx
  src/main/webapp/app/shared/utils/Utils.tsx
  src/main/webapp/app/store/AnnotationStore.ts
Labels: fix

#568 Increase pageable max-page-size to 5000
  src/main/resources/config/application.yml
Labels: fix

#569 Do not show gene name when alteration includes the gene name in the alteration page
  src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
Labels: fix

#570 Update News for data v2.10 release
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
Labels: fix

#571 Fix issue user authorities do not show in user details page
  src/main/webapp/app/pages/userPage/UserPage.tsx
Labels: fix

#572 Update LoE page & About page
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/LevelOfEvidencePage.tsx
  src/main/webapp/content/files/levelOfEvidence/AAC/Mapping_OncoKB_and_AMP_ASCO_CAP_LOfE.pdf
  src/main/webapp/content/files/levelOfEvidence/AAC/Mapping_OncoKB_and_AMP_ASCO_CAP_LOfE.ppt
  src/main/webapp/content/files/levelOfEvidence/V2/LevelsOfEvidence.pdf
  src/main/webapp/content/files/levelOfEvidence/V2/LevelsOfEvidence.ppt
  src/main/webapp/content/images/level_AAC.png
  src/main/webapp/content/images/level_V2.png
  src/main/webapp/content/images/process.png
Labels: fix

#566 Update response for Google/Baidu checking
  src/main/java/org/mskcc/cbio/oncokb/service/MailService.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
  src/main/resources/templates/mail/tokenHasBeenExposed.html
  src/main/resources/templates/mail/tokenHasBeenExposedToUser.html
Labels: enhancement

#573 Fix URL paramater bug
  src/main/webapp/app/pages/HomePage.tsx
  src/main/webapp/app/pages/LevelOfEvidencePage.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
  src/main/webapp/app/shared/utils/Utils.tsx
Labels: bug

#576 Fix actionable gene page child component status issue
  src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx
  src/main/webapp/app/pages/actionableGenesPage/LevelSelectionRow.tsx
Labels: bug

#577 Update the citations column default sorting method
  src/main/webapp/app/pages/genePage/GenePage.tsx
  src/main/webapp/app/shared/utils/ReactTableUtils.ts
  src/main/webapp/app/shared/utils/Utils.tsx
Labels: fix

#578 Remove reset key valid time restriction
  src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
Labels: fix
