Repository oncokb/oncokb-public, pull requests merged in 2020-10, with the labels that each got.

#528 Update none faculty COI link
  src/main/webapp/app/config/constants.tsx
Labels: fix

#529 Include tab description in the gene page
  src/main/webapp/app/components/ReportIssue.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
Labels: feature

#531 Update to jhipster 6.8.0
  .yo-rc.json
  pom.xml
  src/main/java/org/mskcc/cbio/oncokb/service/UserMailsService.java
  src/main/resources/config/application.yml
  src/test/java/org/mskcc/cbio/oncokb/web/rest/UserDetailsResourceIT.java
  src/test/java/org/mskcc/cbio/oncokb/web/rest/errors/ExceptionTranslatorIT.java
Labels: dependencies

#526 Allow admin to change token expiration date
  package.json
  src/main/webapp/app/components/calendarButton/CalendarButton.tsx
  src/main/webapp/app/components/tokenInputGroups/TokenInputGroups.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/AccountPage.tsx
  src/main/webapp/app/pages/userPage/UserPage.tsx
  yarn.lock
Labels: feature

#533 Update to jhipster 6.10.3
  .yo-rc.json
  README.md
  package.json
  pom.xml
  src/main/java/org/mskcc/cbio/oncokb/config/JacksonConfiguration.java
  src/main/java/org/mskcc/cbio/oncokb/config/LocaleConfiguration.java
  src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenServiceImpl.java
  src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenStatsServiceImpl.java
  src/main/java/org/mskcc/cbio/oncokb/service/impl/UserDetailsServiceImpl.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/MailsController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UserResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/errors/ExceptionTranslator.java
  src/main/resources/config/application.yml
  src/main/webapp/index.html
  src/test/java/org/mskcc/cbio/oncokb/RedisTestContainerExtension.java
  src/test/java/org/mskcc/cbio/oncokb/config/timezone/HibernateTimeZoneIT.java
  src/test/java/org/mskcc/cbio/oncokb/web/rest/UserResourceIT.java
  src/test/resources/config/application.yml
  webpack/webpack.common.js
  yarn.lock
Labels: dependencies

#535 Automatically publish docker image when a release is published
  .github/workflows/docker-release.yml
  .github/workflows/sentry-release.yml
Labels: devops

#539 Fix redis cache & Update token extension calendar component
  src/main/java/org/mskcc/cbio/oncokb/config/CacheConfiguration.java
  src/main/java/org/mskcc/cbio/oncokb/config/cache/TokenCacheResolver.java
  src/main/java/org/mskcc/cbio/oncokb/repository/TokenRepository.java
  src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenServiceImpl.java
  src/main/webapp/app/components/calendarButton/CalendarButton.tsx
  src/main/webapp/app/pages/userPage/UserPage.tsx
Labels: fix

#542 Fix docker push action issue
  .github/release-drafter.yml
  .github/workflows/docker-release.yml
  .github/workflows/update-pom.yml
Labels: fix

#543 Add endpoint to generate reset key & Add Quick Tools in user page
  src/main/java/org/mskcc/cbio/oncokb/config/Constants.java
  src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java
  src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
  src/main/webapp/app/pages/userPage/UserPage.tsx
  src/main/webapp/app/shared/api/generated/API-docs.json
  src/main/webapp/app/shared/api/generated/API.ts
  src/main/webapp/app/shared/utils/PromiseUtils.ts
Labels: feature

#544 Apply Recaptcha to Front-end Only
  package.json
  pom.xml
  src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java
  src/main/java/org/mskcc/cbio/oncokb/security/uuid/UUIDFilter.java
  src/main/webapp/app/App.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/index.tsx
  src/main/webapp/app/indexUtils.tsx
  src/main/webapp/app/routes/routes.tsx
  src/main/webapp/app/shared/auth/RecaptchaBoundaryRoute.tsx
  src/main/webapp/app/store/WindowStore.ts
  yarn.lock
Labels: feature
