Repository oncokb/oncokb-public, pull requests merged in 2020-07, with the labels that each got.

#456 Include OncoKB API Webinar & Update URL when the tutorials modal is opened
  src/main/webapp/app/pages/AboutPage.tsx
Labels: feature

#457 Include current level in URL when toggling levels of evidence page
  src/main/webapp/app/components/Header.tsx
  src/main/webapp/app/pages/LevelOfEvidencePage.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/content/images/level_AAC.png
Labels: feature

#455 Update token usage by cronjob instead of basing on actually API calls
  .jhipster/TokenStats.json
  .yo-rc.json
  src/main/java/org/mskcc/cbio/oncokb/domain/TokenStats.java
  src/main/java/org/mskcc/cbio/oncokb/querydomain/UserTokenUsage.java
  src/main/java/org/mskcc/cbio/oncokb/repository/TokenStatsRepository.java
  src/main/java/org/mskcc/cbio/oncokb/service/TokenStatsService.java
  src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenServiceImpl.java
  src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenStatsServiceImpl.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/ApiProxy.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
  src/main/resources/config/liquibase/changelog/20190826144658_added_entity_TokenStats.xml
  src/main/resources/config/liquibase/fake-data/token_stats.csv
  src/test/java/org/mskcc/cbio/oncokb/web/rest/TokenStatsResourceIT.java
Labels: feature

#459 Make sure a token is generated after account is approved/created
  src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
Labels: fix

#458 Add a property, renewable, to indicate whether the token can be renewed
  .jhipster/Token.json
  src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java
  src/main/java/org/mskcc/cbio/oncokb/domain/Token.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/TokenResource.java
  src/main/resources/config/liquibase/changelog/20190823204705_added_entity_Token.xml
  src/main/resources/config/liquibase/fake-data/token.csv
  src/main/resources/config/liquibase/fake-data/token_stats.csv
  src/test/java/org/mskcc/cbio/oncokb/web/rest/TokenResourceIT.java
Labels: feature

#460 Specify account expiration days if is trial account when creating account by admin
  src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UserResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/ManagedUserVM.java
  src/main/webapp/app/components/newAccountForm/NewAccountForm.tsx
  src/main/webapp/app/pages/CreateAccountPage.tsx
  src/main/webapp/app/shared/api/generated/API-docs.json
  src/main/webapp/app/shared/api/generated/API.ts
  src/test/java/org/mskcc/cbio/oncokb/web/rest/AccountResourceIT.java
Labels: feature

#461 Make sure the trial account cannot be renewed
  src/main/java/org/mskcc/cbio/oncokb/security/uuid/TokenProvider.java
  src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/AuditResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/TokenResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/TokenStatsResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UserResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UserUUIDController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/ManagedUserVM.java
  src/main/resources/config/liquibase/fake-data/token.csv
  src/main/webapp/app/components/newAccountForm/NewAccountForm.tsx
  src/main/webapp/app/shared/api/generated/API-docs.json
  src/main/webapp/app/shared/api/generated/API.ts
  src/test/java/org/mskcc/cbio/oncokb/web/rest/AccountResourceIT.java
Labels: fix

#462 Fix the issue when MSK is in the account whitelist
  k8s/oncokb-public-local.yml
  pom.xml
  src/main/docker/app.yml
  src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
Labels: fix

#463 Update the liquibase history to be able to deploy to production
  src/main/resources/config/liquibase/changelog/20190823204705_added_entity_Token.xml
  src/main/resources/config/liquibase/changelog/20190826144658_added_entity_TokenStats.xml
Labels: fix

#464 Update Readme
  README.md
Labels: documentation

#465 Update for data release 2.5
  k8s/oncokb-public-local.yml
  pom.xml
  src/main/docker/app.yml
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
Labels: fix

#466 Update Team Page
  src/main/webapp/app/pages/TeamPage.tsx
Labels: fix

#468 Token can/not be renewed & Calculate token usage through cronjob
  .jhipster/Token.json
  .jhipster/TokenStats.json
  .yo-rc.json
  src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java
  src/main/java/org/mskcc/cbio/oncokb/domain/Token.java
  src/main/java/org/mskcc/cbio/oncokb/domain/TokenStats.java
  src/main/java/org/mskcc/cbio/oncokb/querydomain/UserTokenUsage.java
  src/main/java/org/mskcc/cbio/oncokb/repository/TokenStatsRepository.java
  src/main/java/org/mskcc/cbio/oncokb/security/uuid/TokenProvider.java
  src/main/java/org/mskcc/cbio/oncokb/service/TokenStatsService.java
  src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
  src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenServiceImpl.java
  src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenStatsServiceImpl.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/ApiProxy.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/AuditResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/TokenResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/TokenStatsResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UserResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UserUUIDController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/ManagedUserVM.java
  src/main/resources/config/liquibase/changelog/20190823204705_added_entity_Token.xml
  src/main/resources/config/liquibase/changelog/20190826144658_added_entity_TokenStats.xml
  src/main/resources/config/liquibase/fake-data/token.csv
  src/main/resources/config/liquibase/fake-data/token_stats.csv
  src/main/webapp/app/components/newAccountForm/NewAccountForm.tsx
  src/main/webapp/app/shared/api/generated/API-docs.json
  src/main/webapp/app/shared/api/generated/API.ts
  src/test/java/org/mskcc/cbio/oncokb/web/rest/AccountResourceIT.java
  src/test/java/org/mskcc/cbio/oncokb/web/rest/TokenResourceIT.java
  src/test/java/org/mskcc/cbio/oncokb/web/rest/TokenStatsResourceIT.java
Labels: feature

#471 Avoid infinity refresh loop
  src/main/java/org/mskcc/cbio/oncokb/security/uuid/TokenProvider.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/ClientForwardController.java
  src/main/resources/config/application-prod.yml
  src/main/webapp/app/components/userMessager/UserMessage.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/index.tsx
  src/main/webapp/app/indexUtils.tsx
  src/main/webapp/app/store/AuthenticationStore.ts
  src/main/webapp/index.html
Labels: fix

#473 For publicwebsite token fetch, avoid the cache
  src/main/java/org/mskcc/cbio/oncokb/config/Constants.java
  src/main/java/org/mskcc/cbio/oncokb/repository/TokenRepository.java
  src/main/java/org/mskcc/cbio/oncokb/security/uuid/TokenProvider.java
  src/main/java/org/mskcc/cbio/oncokb/service/TokenService.java
  src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenServiceImpl.java
Labels: fix

#475 Domain Check
  src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java
Labels: fix

#476 Update token usage for the ones without any stats
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
Labels: fix

#478 Skip the slack mentions when in the DEV profile
  src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java
Labels: fix

#480 Using localStorage to set client api
  README.md
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/shared/api/clientInstance.ts
  src/main/webapp/app/shared/api/oncokbClientInstance.ts
  src/main/webapp/app/shared/api/oncokbPrivateClientInstance.ts
  src/main/webapp/app/shared/utils/DevUtils.ts
Labels: feature

#482 Update news for data release v2.6
  k8s/oncokb-public-local.yml
  pom.xml
  src/main/docker/app.yml
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
Labels: fix

#483 Gene page improvement
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
Labels: feature
