Repository oncokb/oncokb-public, pull requests merged in 2020-11, with the labels that each got.

#545 Usage Analysis Page
  pom.xml
  src/main/java/org/mskcc/cbio/oncokb/config/application/AWSProperties.java
  src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UsageSummary.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UserOverviewUsage.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UserUsage.java
  src/main/resources/config/application-dev.yml
  src/main/resources/config/application-prod.yml
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/AccountPage.tsx
  src/main/webapp/app/pages/menus/account.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UsageAnalysisPage.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UsageDetailsTable.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UserUsagePage.tsx
  src/main/webapp/app/routes/AdminRoutes.tsx
  src/main/webapp/app/shared/api/generated/API.ts
Labels: feature

#547 oncokb usage page update
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UserOverviewUsage.java
  src/main/webapp/app/pages/usageAnalysisPage/UsageAnalysisPage.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UsageDetailsTable.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UserUsagePage.tsx
  src/main/webapp/app/shared/api/generated/API.ts
Labels: enhancement

#548 Update News for data v2.9
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
  src/main/webapp/app/shared/links/PMIDLink.tsx
Labels: fix

#549 Update News
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
Labels: fix

#553 Show MSK log when it's in large screen
  src/main/webapp/app/components/Header.tsx
Labels: fix

#551 Update the cancer gene list references
  src/main/webapp/app/pages/CancerGenesPage.tsx
Labels: fix

#555 Increase the user size when pulling users information
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/sendEmails/SendEmailsPage.tsx
  src/main/webapp/app/pages/userManagement/UserDetailsPage.tsx
  src/main/webapp/app/pages/userManagement/UserManagementPage.tsx
Labels: fix
