Repository oncokb/oncokb-public, pull requests merged in 2021-02, with the labels that each got.

#610 Fix email template signature issue
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
  src/main/resources/templates/mail/approvalMSKInCommercial.html
  src/main/resources/templates/mail/clarifyAcademicUseWithoutInstituteEmail.html
  src/main/resources/templates/mail/clarifyLicenseInForProfileCompany.html
  src/main/resources/templates/mail/licenseReview.html
  src/main/resources/templates/mail/sendIntakeForm.html
  src/main/resources/templates/mail/trialAccountIsAboutToExpire.html
  src/main/resources/templates/mail/verifyEmailBeforeAccountExpires.html
Labels: fix

#612 Fix email template signature issue
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
  src/main/resources/templates/mail/approvalMSKInCommercial.html
  src/main/resources/templates/mail/clarifyAcademicUseWithoutInstituteEmail.html
  src/main/resources/templates/mail/clarifyLicenseInForProfileCompany.html
  src/main/resources/templates/mail/licenseReview.html
  src/main/resources/templates/mail/sendIntakeForm.html
  src/main/resources/templates/mail/trialAccountIsAboutToExpire.html
  src/main/resources/templates/mail/verifyEmailBeforeAccountExpires.html
Labels: fix

#608 update usage-analysis-page
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/ResourceModel.java
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/usageAnalysisPage/ResourceUsageDetailsPage.tsx
  src/main/webapp/app/pages/usageAnalysisPage/ResourceUsageDetailsTable.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UsageAnalysisPage.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UsageDetailsTable.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UsageToggleGroup.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UserUsageDetailsPage.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UserUsageDetailsTable.tsx
  src/main/webapp/app/routes/AdminRoutes.tsx
  src/main/webapp/app/shared/api/generated/API.ts
  src/main/webapp/app/shared/utils/Utils.tsx
Labels: enhancement, feature

#613 Update the Team page to include External Advisory Board
  src/main/webapp/app/pages/teamPage/COILinkout.tsx
  src/main/webapp/app/pages/teamPage/TeamMember.tsx
  src/main/webapp/app/pages/teamPage/TeamPage.tsx
Labels: feature

#614 Send feedback through api with restricted fields
  src/main/java/org/mskcc/cbio/oncokb/service/MailService.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/MailsController.java
  src/main/webapp/app/Main.tsx
  src/main/webapp/app/components/ReportIssue.tsx
  src/main/webapp/app/components/SuggestCuration.tsx
  src/main/webapp/app/components/feedback/FeedbackForm.tsx
  src/main/webapp/app/components/feedback/FeedbackIcon.tsx
  src/main/webapp/app/components/feedback/FeedbackModal.tsx
  src/main/webapp/app/components/feedback/types.ts
  src/main/webapp/app/components/oncokbSearch/OncoKBSearch.tsx
  src/main/webapp/app/components/searchOption/SearchOption.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/CancerGenesPage.tsx
  src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
  src/main/webapp/app/shared/api/generated/API-docs.json
  src/main/webapp/app/shared/api/generated/API.ts
  src/main/webapp/app/store/AppStore.ts
Labels: feature

#615 Update news for v3.1 release
  src/main/webapp/app/components/SimpleTable.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/newsPage/ChangedAnnotatonListItem.tsx
  src/main/webapp/app/pages/newsPage/Links.tsx
  src/main/webapp/app/pages/newsPage/NewsList.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
  src/main/webapp/app/pages/newsPage/main.module.scss
Labels: fix

#622 Improve mobile viewer experience
  src/main/webapp/app/pages/HomePage.tsx
  src/main/webapp/app/pages/annotationPage/AlterationInfo.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
  src/main/webapp/app/pages/newsPage/ChangedAnnotatonListItem.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
  src/main/webapp/app/pages/newsPage/UpdatedTxImplListItem.tsx
  src/main/webapp/app/pages/newsPage/UpdatedTxImplOldFormatListItem.tsx
  src/main/webapp/app/pages/teamPage/TeamPage.tsx
Labels: enhancement

#621 Fix sorting issue
  screenshot-test/__baseline_snapshots__/Actionable Genes Page Levels Selected with Login-snap.png
  screenshot-test/__baseline_snapshots__/Actionable Genes Page Levels Selected without Login-snap.png
  screenshot-test/__baseline_snapshots__/Actionable Genes Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Actionable Genes Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Alteration Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Alteration Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Gene Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Gene Page without Login-snap.png
  src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx
  src/main/webapp/app/pages/annotationPage/AnnotationPageTable.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
  src/main/webapp/app/pages/genePage/GenePageTable.tsx
  src/main/webapp/app/shared/utils/ReactTableUtils.ts
  src/main/webapp/app/shared/utils/Utils.tsx
Labels: fix

#624 Fix the 3A/3B mapping in the gene page
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/HomePage.tsx
  src/main/webapp/app/pages/actionableGenesPage/LevelSelectionRow.tsx
Labels: fix

#626 Update the logic of emailVerified
  src/main/java/org/mskcc/cbio/oncokb/service/dto/UserDTO.java
  src/main/webapp/app/pages/userManagement/UserDetailsPage.tsx
  src/main/webapp/app/pages/userManagement/UserManagementPage.tsx
  src/main/webapp/app/routes/UserManagementRoutes.tsx
Labels: fix

#623 Support resistance mutation
  package.json
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/shared/utils/ReactTableUtils.ts
  yarn.lock
Labels: feature
