Repository oncokb/oncokb-public, pull requests merged in 2021-01, with the labels that each got.

#579 fix footer clicking bug
  src/main/webapp/app/components/Footer.module.scss
  src/main/webapp/app/index.scss
Labels: bug

#584 prettier
  src/main/webapp/app/appConfig.ts
  src/main/webapp/app/components/CitationText.tsx
  src/main/webapp/app/components/CitationTooltip.tsx
  src/main/webapp/app/components/MskccLogo.tsx
  src/main/webapp/app/components/account/AccountPassword.tsx
  src/main/webapp/app/components/account/ActivateAccount.tsx
  src/main/webapp/app/components/account/PasswordResetFinish.tsx
  src/main/webapp/app/components/account/PasswordResetInit.tsx
  src/main/webapp/app/components/loadingIndicator/LoadingIndicator.tsx
  src/main/webapp/app/components/oncokbMutationMapper/FilterUtils.ts
  src/main/webapp/app/components/oncokbMutationMapper/OncogenicityBadgeSelector.tsx
  src/main/webapp/app/components/oncokbMutationMapper/OncokbMutationMapper.tsx
  src/main/webapp/app/components/oncokbSearch/OncoKBSearch.tsx
  src/main/webapp/app/components/searchOption/SearchOption.tsx
  src/main/webapp/app/pages/CreateAccountPage.tsx
  src/main/webapp/app/pages/RegisterPage.tsx
  src/main/webapp/app/pages/TermsPage.tsx
  src/main/webapp/app/pages/newsPage/ChangedAnnotatonListItem.tsx
  src/main/webapp/app/pages/newsPage/NewsList.tsx
  src/main/webapp/app/pages/newsPage/UpdatedTxImplListItem.tsx
  src/main/webapp/app/pages/newsPage/UpdatedTxImplOldFormatListItem.tsx
  src/main/webapp/app/shared/auth/private-route.tsx
  src/main/webapp/app/shared/error/error-boundary.tsx
  src/main/webapp/app/shared/error/page-not-found.tsx
  src/main/webapp/app/shared/links/ContactLink.tsx
  src/main/webapp/app/shared/links/HashLink.tsx
  src/main/webapp/app/shared/password/password-strength-bar.tsx
  src/main/webapp/app/shared/utils/NotificationUtils.tsx
  src/main/webapp/app/store/AppStore.ts
Labels: enhancement

#583 Update to the latest api client
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UsageSummary.java
  src/main/webapp/app/pages/usageAnalysisPage/UsageAnalysisPage.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UsageDetailsTable.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UserUsagePage.tsx
  src/main/webapp/app/shared/api/generated/API-docs.json
  src/main/webapp/app/shared/api/generated/API.ts
Labels: fix

#591 Include reCAPTCHA for user validation
  package.json
  pom.xml
  src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java
  src/main/webapp/app/App.tsx
  src/main/webapp/app/Main.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/index.scss
  src/main/webapp/app/index.tsx
  src/main/webapp/app/routes/routes.tsx
  src/main/webapp/app/shared/auth/RecaptchaBoundaryRoute.tsx
  src/main/webapp/app/shared/button/LoadingButton.tsx
  src/main/webapp/app/store/WindowStore.ts
  yarn.lock
Labels: enhancement, feature

#593 Only execute recaptcha when it's rendered
  src/main/webapp/app/App.tsx
  src/main/webapp/app/store/WindowStore.ts
Labels: fix

#594 Use ErrorAltertUtils to handle OncoKBError
  src/main/webapp/app/components/account/AccountPassword.tsx
  src/main/webapp/app/pages/RegisterPage.tsx
Labels: fix

#595 Move recaptcha logic to App and store a state in AppStore to share
  src/main/webapp/app/App.tsx
  src/main/webapp/app/Main.tsx
  src/main/webapp/app/routes/routes.tsx
  src/main/webapp/app/shared/auth/RecaptchaBoundaryRoute.tsx
  src/main/webapp/app/store/AppStore.ts
  src/main/webapp/app/store/WindowStore.ts
Labels: fix

#601 Release diagnostic/prognostic implications
  .github/release-drafter.yml
  .github/workflows/update-pom.yml
  package.json
  pom.xml
  src/main/webapp/app/components/LevelWithDescription.tsx
  src/main/webapp/app/components/authDownloadButton/AuthDownloadButton.tsx
  src/main/webapp/app/components/levelButton/LevelButton.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/index.module.scss
  src/main/webapp/app/pages/ActionableGenesPage.tsx
  src/main/webapp/app/pages/HomePage.tsx
  src/main/webapp/app/pages/LevelOfEvidencePage.tsx
  src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx
  src/main/webapp/app/pages/actionableGenesPage/LevelSelectionRow.tsx
  src/main/webapp/app/pages/alterationPage/AlterationPage.module.scss
  src/main/webapp/app/pages/alterationPage/AlterationPage.tsx
  src/main/webapp/app/pages/annotationPage/AlterationInfo.tsx
  src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
  src/main/webapp/app/pages/annotationPage/AnnotationPageTable.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
  src/main/webapp/app/pages/genePage/GenePageTable.tsx
  src/main/webapp/app/pages/hgvsgPage/HgvsgPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
  src/main/webapp/app/routes/routes.tsx
  src/main/webapp/app/shared/api/generated/OncoKbAPI-docs.json
  src/main/webapp/app/shared/api/generated/OncoKbAPI.ts
  src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI-docs.json
  src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI.ts
  src/main/webapp/app/shared/auth/RecaptchaBoundaryRoute.tsx
  src/main/webapp/app/shared/auth/private-route.tsx
  src/main/webapp/app/shared/dropdown/CancerTypeSelect.tsx
  src/main/webapp/app/shared/links/LevelOfEvidencePageLink.tsx
  src/main/webapp/app/shared/utils/Utils.tsx
  src/main/webapp/app/store/AnnotationStore.ts
  src/main/webapp/content/files/levelOfEvidence/DX/LevelsOfEvidence.pdf
  src/main/webapp/content/files/levelOfEvidence/DX/LevelsOfEvidence.ppt
  src/main/webapp/content/files/levelOfEvidence/PX/LevelsOfEvidence.pdf
  src/main/webapp/content/files/levelOfEvidence/V2/LevelsOfEvidence.pdf
  src/main/webapp/content/files/levelOfEvidence/V2/LevelsOfEvidence.ppt
  src/main/webapp/content/images/level_DX.png
  src/main/webapp/content/images/level_PX.png
  src/main/webapp/content/images/level_V2.png
  yarn.lock
Labels: feature

#602 Update LoE image/pdf/ppt to the latest
  .github/release-drafter.yml
  .github/workflows/update-pom.yml
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/content/files/levelOfEvidence/AAC/Mapping_OncoKB_and_AMP_ASCO_CAP_LOfE.pdf
  src/main/webapp/content/files/levelOfEvidence/AAC/Mapping_OncoKB_and_AMP_ASCO_CAP_LOfE.ppt
  src/main/webapp/content/files/levelOfEvidence/V2/LevelsOfEvidence.pdf
  src/main/webapp/content/files/levelOfEvidence/V2/LevelsOfEvidence.ppt
  src/main/webapp/content/images/level_AAC.png
  src/main/webapp/content/images/level_V2.png
Labels: fix

#604 Disable recaptcha verifying page
  src/main/webapp/app/shared/auth/RecaptchaBoundaryRoute.tsx
Labels: fix

#605 Use the updated models ClinicalVariant and VariantAnnotation
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx
  src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
  src/main/webapp/app/shared/api/generated/OncoKbAPI-docs.json
  src/main/webapp/app/shared/api/generated/OncoKbAPI.ts
  src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI-docs.json
  src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI.ts
  src/main/webapp/app/shared/utils/Utils.tsx
  src/main/webapp/app/store/AnnotationStore.ts
Labels: fix

#606 Sort actionable gene download file
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx
  src/main/webapp/app/shared/utils/ReactTableUtils.ts
Labels: fix

#607 Only show information with selected reference genome
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx
  src/main/webapp/app/pages/alterationPage/AlterationPage.tsx
  src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
  src/main/webapp/app/pages/hgvsgPage/HgvsgPage.tsx
  src/main/webapp/app/shared/utils/UrlUtils.tsx
  src/main/webapp/app/store/AnnotationStore.ts
Labels: fix

#603 Implement user usage analysis pipeline
  src/main/java/org/mskcc/cbio/oncokb/querydomain/UserTokenUsageWithInfo.java
  src/main/java/org/mskcc/cbio/oncokb/repository/TokenStatsRepository.java
  src/main/java/org/mskcc/cbio/oncokb/service/S3Service.java
  src/main/java/org/mskcc/cbio/oncokb/service/TokenStatsService.java
  src/main/java/org/mskcc/cbio/oncokb/service/impl/TokenStatsServiceImpl.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/ResourceModel.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UsageSummary.java
Labels: feature
