Repository oncokb/oncokb-public, pull requests merged in 2021-09, with the labels that each got.

#701 Update team members
  screenshot-test/__baseline_snapshots__/Team Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Team Page without Login-snap.png
  src/main/webapp/app/pages/teamPage/TeamMember.tsx
  src/main/webapp/app/pages/teamPage/TeamPage.tsx
Labels: enhancement

#702 Update features related to FDA content
  src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx
  src/main/webapp/app/pages/alterationPage/AlterationPage.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
  src/main/webapp/app/pages/hgvsgPage/HgvsgPage.tsx
  src/main/webapp/app/shared/route/types.tsx
Labels: enhancement

#704 Only include sentry when the instance has prod profile
  src/main/java/org/mskcc/cbio/oncokb/OncokbPublicApp.java
  src/main/webapp/app/index.tsx
Labels: fix

#703 Add intro video in the about page
  screenshot-test/App.screenshot.js
  screenshot-test/__baseline_snapshots__/About Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/About Page without Login-snap.png
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/AboutPage.tsx
  src/main/webapp/app/shared/utils/UrlUtils.tsx
  src/main/webapp/app/shared/utils/Utils.tsx
Labels: feature

#687 Slack Integration Improvements
  src/main/java/org/mskcc/cbio/oncokb/domain/UnknownPayload.java
  src/main/java/org/mskcc/cbio/oncokb/domain/UserStatusChecks.java
  src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/MailType.java
  src/main/java/org/mskcc/cbio/oncokb/service/MailService.java
  src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/SlackController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/slack/ActionId.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/slack/BlockId.java
  src/main/resources/i18n/messages.properties
  src/main/resources/templates/mail/alumniEmailAddress.html
  src/main/resources/templates/mail/alumniEmailAddressString.txt
  src/main/resources/templates/mail/clarifyAcademicUseWithoutInstituteEmailString.txt
  src/main/resources/templates/mail/clarifyDuplicateUser.html
  src/main/resources/templates/mail/clarifyDuplicateUserString.txt
  src/main/resources/templates/mail/clarifyLicenseInForProfileCompanyString.txt
  src/main/resources/templates/mail/clarifyUseCase.html
  src/main/resources/templates/mail/clarifyUseCaseString.txt
  src/main/resources/templates/mail/rejectionEmail.html
  src/main/resources/templates/mail/rejectionEmailString.txt
  src/main/webapp/app/shared/api/generated/API-docs.json
Labels: enhancement

#707 Email feature updates
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#User Detail-snap.png
  screenshot-test/__baseline_snapshots__/User Details Page-snap.png
  src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/MailType.java
  src/main/java/org/mskcc/cbio/oncokb/service/MailService.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/MailsController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/errors/BadRequestAlertException.java
  src/main/resources/i18n/messages.properties
  src/main/resources/templates/mail/dataUsageExceedsThreshold.html
  src/main/webapp/app/pages/sendEmails/SendEmailsPage.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UserUsageDetailsPage.tsx
  src/main/webapp/app/pages/userPage/UserPage.tsx
  src/main/webapp/app/shared/alert/ErrorAlertUtils.ts
  src/main/webapp/app/shared/api/generated/API-docs.json
  src/main/webapp/app/shared/api/generated/API.ts
  src/main/webapp/app/shared/route/types.tsx
  src/main/webapp/app/shared/utils/NotificationUtils.tsx
Labels: feature

#710 Update news for data v3.7
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
Labels: fix

#713 Include all intro videos in the about page
  screenshot-test/App.screenshot.js
  screenshot-test/__baseline_snapshots__/About Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/About Page without Login-snap.png
  src/main/webapp/app/pages/AboutPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
Labels: feature

#714 Update FDA icons
  src/main/webapp/app/shared/utils/Utils.tsx
Labels: enhancement

#712 Make Redis caching optional
  pom.xml
  src/main/java/org/mskcc/cbio/oncokb/config/CacheConfiguration.java
  src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java
  src/main/java/org/mskcc/cbio/oncokb/config/application/RedisProperties.java
  src/main/java/org/mskcc/cbio/oncokb/config/application/RedisType.java
  src/main/java/org/mskcc/cbio/oncokb/config/cache/CustomCacheManager.java
  src/main/resources/config/application-dev.yml
  src/main/resources/config/application-prod.yml
Labels: feature
