Repository oncokb/oncokb-public, pull requests merged in 2022-09, with the labels that each got.

#885 Expires token when user is inactivated
  src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
Labels: fix

#886 Fix null user in analysis page
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisController.java
  src/main/resources/config/liquibase/fake-data/token.csv
  src/main/webapp/app/pages/usageAnalysisPage/UsageAnalysisPage.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UserUsageDetailsPage.tsx
  src/main/webapp/app/pages/userPage/UserPage.tsx
  src/main/webapp/app/shared/api/generated/API-docs.json
  src/main/webapp/app/shared/api/generated/API.ts
Labels: fix

#890 Use fdaLevel from treatment && Display cancer type exclusion if available
  pom.xml
  screenshot-test/data/api-private-search-variants-fda-ABL1.json
  screenshot-test/data/api-private-search-variants-fda-BRAF.json
  src/main/webapp/app/components/levelButton/LevelButton.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/HomePage.tsx
  src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx
  src/main/webapp/app/pages/actionableGenesPage/LevelSelectionRow.tsx
  src/main/webapp/app/pages/alterationPage/AlterationPage.tsx
  src/main/webapp/app/pages/annotationPage/AlterationTableTabs.tsx
  src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
  src/main/webapp/app/pages/annotationPage/Utils.ts
  src/main/webapp/app/pages/genePage/GeneAdditionalInfoTable.tsx
  src/main/webapp/app/pages/genePage/GeneInfo.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
  src/main/webapp/app/pages/genePage/GenePageTable.tsx
  src/main/webapp/app/pages/hgvsgPage/HgvsgPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
  src/main/webapp/app/shared/api/generated/API.ts
  src/main/webapp/app/shared/api/generated/OncoKbAPI-docs.json
  src/main/webapp/app/shared/api/generated/OncoKbAPI.ts
  src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI-docs.json
  src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI.ts
  src/main/webapp/app/shared/utils/Utils.tsx
  src/main/webapp/app/store/AnnotationStore.ts
  src/main/webapp/app/store/AppStore.ts
  src/main/webapp/content/images/oncokb_summary.png
  src/main/webapp/index.html
Labels: feature

#887 Disable traces sampling
  src/main/java/org/mskcc/cbio/oncokb/OncokbPublicApp.java
Labels: devops

#882 Use case added to user page
  src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
  src/main/java/org/mskcc/cbio/oncokb/service/dto/useradditionalinfo/AdditionalInfoDTO.java
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/userPage/UserPage.tsx
  src/test/java/org/mskcc/cbio/oncokb/web/rest/TestUtil.java
Labels: enhancement

#893 Use long instead of int in data usage models
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UsageSummary.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UserOverviewUsage.java
Labels: fix

#894 Show All Solid/Liquid Tumors in the actionable genes page
  src/main/webapp/app/shared/dropdown/CancerTypeSelect.tsx
Labels: fix

#895 Update sendFrom for license options email & Add sendBy from slack
  pom.xml
  src/main/java/org/mskcc/cbio/oncokb/service/MailService.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/SlackController.java
  src/test/java/org/mskcc/cbio/oncokb/service/MailServiceIT.java
Labels: enhancement

#897 Direct alteration number to actionable genes page
  src/main/webapp/app/pages/HomePage.tsx
Labels: enhancement

#896 Improve User Details Page and Company Page's User Dropdown Performances
  screenshot-test/App.screenshot.js
  src/main/java/org/mskcc/cbio/oncokb/config/CacheConfiguration.java
  src/main/java/org/mskcc/cbio/oncokb/config/cache/UserCacheResolver.java
  src/main/java/org/mskcc/cbio/oncokb/repository/UserDetailsRepository.java
  src/main/java/org/mskcc/cbio/oncokb/repository/UserRepository.java
  src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
  src/main/java/org/mskcc/cbio/oncokb/service/dto/UserDTO.java
  src/main/java/org/mskcc/cbio/oncokb/service/dto/useradditionalinfo/Activation.java
  src/main/java/org/mskcc/cbio/oncokb/service/dto/useradditionalinfo/AdditionalInfoDTO.java
  src/main/java/org/mskcc/cbio/oncokb/service/dto/useradditionalinfo/Contact.java
  src/main/java/org/mskcc/cbio/oncokb/service/dto/useradditionalinfo/LicenseAgreement.java
  src/main/java/org/mskcc/cbio/oncokb/service/dto/useradditionalinfo/TrialAccount.java
  src/main/java/org/mskcc/cbio/oncokb/service/dto/useradditionalinfo/UserCompany.java
  src/main/java/org/mskcc/cbio/oncokb/service/mapper/UserMapper.java
  src/main/webapp/app/config/constants.tsx
Labels: enhancement
