Repository oncokb/oncokb-public, pull requests merged in 2022-01, with the labels that each got.

#775 Upgrade github action versions
  .github/workflows/docker-release.yml
  .github/workflows/github-ci.yml
  .github/workflows/screenshot-test.yml
  .github/workflows/update-pom.yml
  screenshot-test/__baseline_snapshots__/About Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/About Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Account Settings Page-snap.png
  screenshot-test/__baseline_snapshots__/Actionable Genes Page Levels Selected with Login-snap.png
  screenshot-test/__baseline_snapshots__/Actionable Genes Page Levels Selected without Login-snap.png
  screenshot-test/__baseline_snapshots__/Actionable Genes Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Actionable Genes Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Alteration Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Alteration Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Cancer Genes Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Cancer Genes Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Gene Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Gene Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/HGVSg Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/HGVSg Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Home Page DX with Login-snap.png
  screenshot-test/__baseline_snapshots__/Home Page DX without Login-snap.png
  screenshot-test/__baseline_snapshots__/Home Page PX with Login-snap.png
  screenshot-test/__baseline_snapshots__/Home Page PX without Login-snap.png
  screenshot-test/__baseline_snapshots__/Home Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Home Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page AAC with Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page AAC without Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page DX with Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page DX without Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page PX with Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page PX without Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page V1 with Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page V1 without Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Login Page-snap.png
  screenshot-test/__baseline_snapshots__/Team Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Team Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Terms Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Terms Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#Resource Detail-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#Resource Overview-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#User Detail-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#User Overview-snap.png
  screenshot-test/__baseline_snapshots__/User Details Page-snap.png
  screenshot-test/__baseline_snapshots__/Users Infomation Page-snap.png
Labels: devops

#779 Adjust page layout to have 13inch screen using the container-fluid
  screenshot-test/__baseline_snapshots__/About Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/About Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Account Settings Page-snap.png
  screenshot-test/__baseline_snapshots__/Actionable Genes Page Levels Selected with Login-snap.png
  screenshot-test/__baseline_snapshots__/Actionable Genes Page Levels Selected without Login-snap.png
  screenshot-test/__baseline_snapshots__/Actionable Genes Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Actionable Genes Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Alteration Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Alteration Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Cancer Genes Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Cancer Genes Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Gene Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Gene Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/HGVSg Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/HGVSg Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Home Page DX with Login-snap.png
  screenshot-test/__baseline_snapshots__/Home Page DX without Login-snap.png
  screenshot-test/__baseline_snapshots__/Home Page PX with Login-snap.png
  screenshot-test/__baseline_snapshots__/Home Page PX without Login-snap.png
  screenshot-test/__baseline_snapshots__/Home Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Home Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page AAC with Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page AAC without Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page DX with Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page DX without Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page PX with Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page PX without Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page V1 with Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page V1 without Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Login Page-snap.png
  screenshot-test/__baseline_snapshots__/Team Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Team Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Terms Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Terms Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#Resource Detail-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#Resource Overview-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#User Detail-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#User Overview-snap.png
  screenshot-test/__baseline_snapshots__/User Details Page-snap.png
  screenshot-test/__baseline_snapshots__/Users Infomation Page-snap.png
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/LevelOfEvidencePage.tsx
  src/main/webapp/app/variables.scss
Labels: style tweak

#780 Show trial expiration date only when the trial is activated by user
  src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java
Labels: bug

#784 Include ensembl info as a table & Include categorical alteration description
  screenshot-test/App.screenshot.js
  screenshot-test/__baseline_snapshots__/Gene Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Gene Page without Login-snap.png
  screenshot-test/data/api-private-utils-ensembleGenes-ABL1.json
  src/main/webapp/app/components/MskimpactLink.tsx
  src/main/webapp/app/components/barChart/BarChart.tsx
  src/main/webapp/app/components/oncokbMutationMapper/OncogenicityBadgeSelector.tsx
  src/main/webapp/app/components/oncokbMutationMapper/OncogenicityCheckboxes.tsx
  src/main/webapp/app/components/oncokbMutationMapper/OncokbMutationMapper.tsx
  src/main/webapp/app/components/oncokbMutationMapper/oncokbMutationMapper.module.scss
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/alterationPage/AlterationPage.module.scss
  src/main/webapp/app/pages/alterationPage/AlterationPage.tsx
  src/main/webapp/app/pages/annotationPage/AlterationInfo.tsx
  src/main/webapp/app/pages/annotationPage/AlterationTableTabs.tsx
  src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
  src/main/webapp/app/pages/genePage/GeneAdditionalInfoTable.tsx
  src/main/webapp/app/pages/genePage/GeneInfo.tsx
  src/main/webapp/app/pages/genePage/GenePage.module.scss
  src/main/webapp/app/pages/genePage/GenePage.tsx
  src/main/webapp/app/pages/genePage/OncokbLollipopPlot.tsx
  src/main/webapp/app/pages/genePage/ReferenceGenomeInfo.tsx
  src/main/webapp/app/pages/hgvsgPage/HgvsgPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
  src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI-docs.json
  src/main/webapp/app/shared/api/generated/OncoKbPrivateAPI.ts
  src/main/webapp/app/shared/icons/ShowHideToggleIcon.tsx
  src/main/webapp/app/shared/utils/UrlUtils.tsx
  src/main/webapp/app/shared/utils/Utils.tsx
  src/main/webapp/app/store/AnnotationStore.ts
Labels: feature

#786 Add action to auto update after commit to master branch
  .github/workflows/after-master-commit.yml
  .github/workflows/release-management.yml
  .github/workflows/update-pom.yml
  .version-level
Labels: devops

#789 Send approval email when regular user is automatically approved
  src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
Labels: fix

#788 Allow changing user's first/last names
  screenshot-test/__baseline_snapshots__/User Details Page-snap.png
  src/main/webapp/app/components/account/ActivateTrialFinish.tsx
  src/main/webapp/app/components/newAccountForm/NewAccountForm.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/userPage/UserPage.tsx
  src/main/webapp/app/shared/utils/FormValidationUtils.tsx
Labels: feature

#787 Create page to create company users in batch
  src/main/java/org/mskcc/cbio/oncokb/web/rest/errors/LoginAlreadyUsedException.java
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/CreateAccountPage.tsx
  src/main/webapp/app/pages/CreateCompanyUsersPage.tsx
  src/main/webapp/app/pages/companyPage/CompanyPage.tsx
  src/main/webapp/app/routes/routes.tsx
  src/main/webapp/app/shared/modal/SimpleConfirmModal.tsx
Labels: feature

#792 Do not check token in google/baidu
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
Labels: fix

#794 Update Sentry & Capture all ApiProxy error
  pom.xml
  src/main/java/org/mskcc/cbio/oncokb/web/rest/ApiProxy.java
Labels: fix

#791 Change logic for determining if user is on trial
  src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UserUUIDController.java
  src/main/webapp/app/pages/CreateCompanyUsersPage.tsx
  src/main/webapp/app/pages/userPage/UserPage.tsx
  src/main/webapp/app/shared/table/UserTable.tsx
  src/main/webapp/app/store/AuthenticationStore.ts
Labels: fix

#800 Remove headers created with HeaderUtil
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CompanyDomainResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CompanyResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UserDetailsResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UserMailsResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/errors/ExceptionTranslator.java
Labels: fix

#805 Fix trial account slack visual bug
  src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java
Labels: fix

#807 Pass hash parameters from ApiAccessPageNavTab to pages
  src/main/webapp/app/pages/apiAccessGroup/ApiAccessPageNavTab.tsx
Labels: fix

#808 Use exact alt/name for matchedAlteration
  src/main/webapp/app/store/AnnotationStore.ts
Labels: fix

#810 Update backend sentry settings
  pom.xml
  src/main/java/org/mskcc/cbio/oncokb/OncokbPublicApp.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/ApiProxy.java
Labels: devops

#811 Update sentry-react & Fix error when async react-select options failed
  package.json
  src/main/webapp/app/components/oncokbSearch/OncoKBSearch.tsx
  yarn.lock
Labels: fix

#812 Ignore known sentry issues and common errors
  src/main/webapp/app/index.tsx
Labels: fix

#813 Include the source map in the production build & Send source map to Sentry
  .github/workflows/docker-sentry-release.yml
  .github/workflows/sentry-release.yml
  webpack/webpack.prod.js
Labels: fix
