Repository oncokb/oncokb-public, pull requests merged in 2023-03, with the labels that each got.

#948 Bring the tab description to the front
  src/main/webapp/app/components/feedback/FeedbackIcon.tsx
  src/main/webapp/app/pages/annotationPage/AlterationTableTabs.tsx
Labels: fix

#947 Update page titles to include OncoKB and MSKCC post fixes
  src/main/webapp/app/App.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/AboutPage.tsx
  src/main/webapp/app/pages/CancerGenesPage.tsx
  src/main/webapp/app/pages/FAQPage.tsx
  src/main/webapp/app/pages/LevelOfEvidencePage.tsx
  src/main/webapp/app/pages/aboutGroup/AboutPageNavTab.tsx
  src/main/webapp/app/pages/aboutGroup/FdaRecognitionPage.tsx
  src/main/webapp/app/pages/actionableGenesPage/ActionableGenesPage.tsx
  src/main/webapp/app/pages/alterationPage/AlterationPage.tsx
  src/main/webapp/app/pages/apiAccessGroup/APIAccessPage.tsx
  src/main/webapp/app/pages/apiAccessGroup/TermsPage.tsx
  src/main/webapp/app/pages/companyPage/CompanyPage.tsx
  src/main/webapp/app/pages/genePage/GenePage.tsx
  src/main/webapp/app/pages/hgvsgPage/HgvsgPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/pages/teamPage/TeamPage.tsx
  src/main/webapp/app/pages/userPage/UserPage.tsx
  src/main/webapp/app/pages/yearEndSummaryPage/YearEndSummaryPage.tsx
  src/main/webapp/app/shared/utils/Utils.tsx
Labels: enhancement

#946 Update robots.txt and general sitemap
  src/main/resources/templates/sitemap/sitemapGeneral.xml
  src/main/resources/templates/txt/robots.txt
Labels: enhancement

#951 Add zIndex to cancer type select in annotation page
  src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
Labels: fix

#952 Update titles based on feedbacks
  screenshot-test/__baseline_snapshots__/About Page without Login-snap.png
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/shared/utils/Utils.tsx
Labels: fix

#956 Do not display lollipop in gene page if no portal alterations are related
  src/main/webapp/app/pages/genePage/GenePage.tsx
Labels: enhancement

#953 Add Gene links in tables in news page
  src/main/webapp/app/pages/newsPage/ChangedAnnotatonListItem.tsx
  src/main/webapp/app/pages/newsPage/NewsList.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
  src/main/webapp/app/pages/newsPage/UpdatedTxImplListItem.tsx
  src/main/webapp/app/pages/newsPage/Util.tsx
Labels: feature

#960 Include drug description column and shorten the text by number of words
  src/main/webapp/app/oncokb-frontend-commons/src/components/LongText.tsx
  src/main/webapp/app/pages/annotationPage/AlterationTableTabs.tsx
  src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
Labels: feature
