Repository oncokb/oncokb-public, pull requests merged in 2024-10, with the labels that each got.

#1159 Show company ID
  screenshot-test/__baseline_snapshots__/Companies Information Page-snap.png
  src/main/webapp/app/pages/companyManagement/CompanyDetailsPage.tsx
Labels: enhancement

#1146 Modify company data schema to include licensing details
  .jhipster/Company.json
  jhipster-jdl.jdl
  screenshot-test/__baseline_snapshots__/Company Details Page-snap.png
  screenshot-test/data/api-companies.json
  screenshot-test/data/api-company-details.json
  src/main/java/org/mskcc/cbio/oncokb/domain/Company.java
  src/main/java/org/mskcc/cbio/oncokb/service/dto/CompanyDTO.java
  src/main/java/org/mskcc/cbio/oncokb/service/dto/companyadditionalinfo/CompanyAdditionalInfoDTO.java
  src/main/java/org/mskcc/cbio/oncokb/service/dto/companyadditionalinfo/CompanyLicense.java
  src/main/java/org/mskcc/cbio/oncokb/service/dto/companyadditionalinfo/CompanyTermination.java
  src/main/java/org/mskcc/cbio/oncokb/service/mapper/CompanyMapper.java
  src/main/resources/config/liquibase/changelog/20240829165533_added_additionalInfo_to_Company.xml
  src/main/resources/config/liquibase/master.xml
  src/main/webapp/app/components/newAccountForm/NewAccountForm.tsx
  src/main/webapp/app/components/newCompanyForm/NewCompanyForm.tsx
  src/main/webapp/app/pages/companyPage/CompanyAdditionalInfo.tsx
  src/main/webapp/app/pages/companyPage/CompanyPage.tsx
  src/main/webapp/app/shared/api/generated/API-docs.json
  src/main/webapp/app/shared/api/generated/API.ts
  src/main/webapp/app/shared/input/FormInputField.tsx
  src/main/webapp/app/shared/select/FormSelectWithLabelField.tsx
  src/main/webapp/app/shared/textarea/FormTextAreaField.tsx
  src/test/java/org/mskcc/cbio/oncokb/web/rest/CompanyResourceIT.java
Labels: feature

#1161 allow keypress events for textareas
  src/main/webapp/app/components/newCompanyForm/NewCompanyForm.tsx
  src/main/webapp/app/pages/companyPage/CompanyPage.tsx
Labels: fix

#1162 Fix data download
  src/main/webapp/app/pages/apiAccessGroup/APIAccessPage.tsx
Labels: fix

#1151 Added termination warning email button
  screenshot-test/__baseline_snapshots__/Company Details Page-snap.png
  src/main/java/org/mskcc/cbio/oncokb/config/application/ApplicationProperties.java
  src/main/java/org/mskcc/cbio/oncokb/service/MailService.java
  src/main/java/org/mskcc/cbio/oncokb/service/dto/TerminationEmailDTO.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/MailsController.java
  src/main/webapp/app/pages/companyPage/CompanyPage.tsx
  src/main/webapp/app/shared/api/generated/API-docs.json
  src/main/webapp/app/shared/api/generated/API.ts
  src/main/webapp/app/shared/textarea/FormTextAreaField.tsx
  src/main/webapp/app/shared/utils/NotificationUtils.tsx
Labels: feature

#1152 Added endpoints to send company notification email
  .github/workflows/after-master-commit.yml
  .github/workflows/docker-sentry-release.yml
  .github/workflows/github-ci.yml
  src/main/java/org/mskcc/cbio/oncokb/domain/enumeration/MailType.java
  src/main/java/org/mskcc/cbio/oncokb/repository/CompanyRepository.java
  src/main/java/org/mskcc/cbio/oncokb/service/CompanyService.java
  src/main/java/org/mskcc/cbio/oncokb/service/MailService.java
  src/main/java/org/mskcc/cbio/oncokb/service/dto/companyadditionalinfo/CompanyTermination.java
  src/main/java/org/mskcc/cbio/oncokb/service/impl/CompanyServiceImpl.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CompanyResource.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/MailsController.java
  src/main/resources/templates/mail/terminationNotificationEmail.html
  src/main/webapp/app/components/newCompanyForm/NewCompanyForm.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/apiAccessGroup/APIAccessPage.tsx
  src/main/webapp/app/pages/companyPage/CompanyAdditionalInfo.tsx
  src/main/webapp/app/pages/companyPage/CompanyPage.tsx
  src/main/webapp/app/pages/userManagement/UserDetailsPage.tsx
  src/main/webapp/app/shared/api/generated/API-docs.json
  src/main/webapp/app/shared/api/generated/API.ts
  src/main/webapp/app/shared/modal/UserStatusModal.tsx
  src/main/webapp/app/shared/table/UserTable.tsx
  yarn.lock
Labels: feature

#1155 Now can go back 3 year in usage stats
  screenshot-test/__baseline_snapshots__/Company User Details Page-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#Resource Detail-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#Resource Overview-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#User Detail-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#User Overview-snap.png
  screenshot-test/__baseline_snapshots__/User Details Page-snap.png
  screenshot-test/data/api-usage-resources-example.json
  screenshot-test/data/api-usage-summary-resources.json
  screenshot-test/data/api-usage-summary-users.json
  screenshot-test/data/api-usage-users-2021.json
  src/main/java/org/mskcc/cbio/oncokb/config/Swagger2Config.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/ResourceModel.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UsageSummary.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UserOverviewUsage.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UserStats.java
  src/main/webapp/app/components/oncokbTable/HeaderConstants.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/companyPage/CompanyPage.tsx
  src/main/webapp/app/pages/usageAnalysisPage/ResourceUsageDetailsPage.tsx
  src/main/webapp/app/pages/usageAnalysisPage/ResourceUsageDetailsTable.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UsageAnalysisPage.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UsageAnalysisTable.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UsageToggleGroup.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UserUsageDetailsPage.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UserUsageDetailsTable.tsx
  src/main/webapp/app/pages/usageAnalysisPage/usage-analysis-utils.spec.ts
  src/main/webapp/app/pages/usageAnalysisPage/usage-analysis-utils.ts
  src/main/webapp/app/pages/userPage/UserPage.tsx
  src/main/webapp/app/shared/api/generated/API-docs.json
  src/main/webapp/app/shared/api/generated/API.ts
  src/main/webapp/app/shared/texts/UsageText.tsx
  src/test/java/org/mskcc/cbio/oncokb/web/rest/CompanyResourceIT.java
  src/test/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisControllerIT.java
Labels: feature

#1183 Show alteration if it's a relevant alt of the original
  src/main/webapp/app/pages/annotationPage/AnnotationPage.tsx
Labels: fix

#1177 Update news 4.22
  screenshot-test/__baseline_snapshots__/Precision Oncology Therapies Page without Login-snap.png
  src/main/webapp/app/components/SimpleTable.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/companionDiagnosticDevicesPage/companionDiagnosticDevicePage.tsx
  src/main/webapp/app/pages/newsPage/ChangedAnnotationListItem.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
  src/main/webapp/app/pages/oncologyTherapiesPage/oncologyTherapiesPage.tsx
  src/main/webapp/app/shared/links/FdaSubmissionLink.tsx
  src/main/webapp/app/shared/utils/Utils.tsx
  src/main/webapp/content/files/companionDiagnosticDevices/companion_diagnostic_devices.json
  src/main/webapp/content/files/oncologyTherapies/fda_approved_oncology_therapies.json
  src/main/webapp/content/files/oncologyTherapies/fda_approved_oncology_therapies.xlsx
  src/main/webapp/content/images/oncokb_summary.png
  src/main/webapp/index.html
Labels: feature
