Repository oncokb/oncokb-public, pull requests merged in 2024-05, with the labels that each got.

#1111 Update news for v4.16 and introduce CDx page
  screenshot-test/__baseline_snapshots__/About Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Account Settings Page without ROLE_API and not requested-snap.png
  screenshot-test/__baseline_snapshots__/Account Settings Page without ROLE_API and requested-snap.png
  screenshot-test/__baseline_snapshots__/Account Settings Page-snap.png
  screenshot-test/__baseline_snapshots__/Actionable Genes Page Levels Selected without Login-snap.png
  screenshot-test/__baseline_snapshots__/Actionable Genes Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Alteration Page with Cancer Type - Heme with Login-snap.png
  screenshot-test/__baseline_snapshots__/Alteration Page with Cancer Type - Heme without Login-snap.png
  screenshot-test/__baseline_snapshots__/Alteration Page with Cancer Type - Solid with Login-snap.png
  screenshot-test/__baseline_snapshots__/Alteration Page with Cancer Type - Solid without Login-snap.png
  screenshot-test/__baseline_snapshots__/Alteration Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Alteration Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Cancer Genes Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Companies Information Page-snap.png
  screenshot-test/__baseline_snapshots__/Company Details Page-snap.png
  screenshot-test/__baseline_snapshots__/Company User Details Page-snap.png
  screenshot-test/__baseline_snapshots__/Gene Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/Gene Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/HGVSg Page on VUE variant with Login-snap.png
  screenshot-test/__baseline_snapshots__/HGVSg Page with Login-snap.png
  screenshot-test/__baseline_snapshots__/HGVSg Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Home Page DX without Login-snap.png
  screenshot-test/__baseline_snapshots__/Home Page PX without Login-snap.png
  screenshot-test/__baseline_snapshots__/Home Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page AAC without Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page DX without Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page PX without Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page V1 without Login-snap.png
  screenshot-test/__baseline_snapshots__/LoE Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Login Page-snap.png
  screenshot-test/__baseline_snapshots__/Precision Oncology Therapies Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Team Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Terms Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#Resource Detail-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#Resource Overview-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#User Detail-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#User Overview-snap.png
  screenshot-test/__baseline_snapshots__/User Details Page-snap.png
  screenshot-test/__baseline_snapshots__/Users Infomation Page-snap.png
  src/main/webapp/app/components/Header.tsx
  src/main/webapp/app/components/oncokbTable/OncoKBTable.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/companionDiagnosticDevicesPage/companionDiagnosticDevicePage.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
  src/main/webapp/app/pages/oncologyTherapiesPage/oncologyTherapiesPage.tsx
  src/main/webapp/app/routes/routes.tsx
  src/main/webapp/app/shared/dropdown/CancerTypeSelect.tsx
  src/main/webapp/app/shared/links/FdaSubmissionLink.tsx
  src/main/webapp/app/shared/utils/FileUtils.ts
  src/main/webapp/app/shared/utils/ReactTableUtils.ts
  src/main/webapp/app/shared/utils/Utils.tsx
  src/main/webapp/content/files/companionDiagnosticDevices/companion_diagnostic_devices.json
  src/main/webapp/content/files/oncologyTherapies/fda_approved_oncology_therapies.json
  src/main/webapp/content/files/oncologyTherapies/fda_approved_oncology_therapies.xlsx
  src/main/webapp/content/images/oncokb_summary.png
  src/main/webapp/index.html
Labels: feature

#1113 Update confirm model type when changing license type with user associated
  src/main/webapp/app/pages/companyPage/CompanyPage.tsx
Labels: fix

#1102 Added canonical link to html head
  src/main/webapp/app/routes/routes.tsx
  src/main/webapp/app/shared/auth/RecaptchaBoundaryRoute.tsx
  src/main/webapp/app/shared/auth/private-route.tsx
  src/main/webapp/app/shared/error/error-boundary-route.tsx
  src/main/webapp/app/shared/route/OncokbRoute.tsx
Labels: fix

#1114 Add allVariantsOfUnknownSignificance endpoint to SecurityConfiguration
  src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java
Labels: feature

#1115 Fix duplicate block id in slack payload
  src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/slack/BlockId.java
Labels: fix

#1116 Added testing slack section in the README
  README.md
Labels: feature

#1118 Sentry updates
  src/main/webapp/app/index.tsx
Labels: devops

#1120 Update to API access request feature
  screenshot-test/__baseline_snapshots__/Company User Details Page-snap.png
  screenshot-test/__baseline_snapshots__/User Details Page-snap.png
  src/main/java/org/mskcc/cbio/oncokb/service/SlackService.java
  src/main/java/org/mskcc/cbio/oncokb/service/UserService.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/AccountResource.java
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/userPage/UserPage.tsx
  src/test/java/org/mskcc/cbio/oncokb/web/rest/AccountResourceIT.java
Labels: fix
