Repository oncokb/oncokb-public, pull requests merged in 2024-01, with the labels that each got.

#1073 Enable user to refresh the expired token when there is a valid one
  screenshot-test/__baseline_snapshots__/Account Settings Page-snap.png
  screenshot-test/__baseline_snapshots__/Company User Details Page-snap.png
  screenshot-test/__baseline_snapshots__/User Details Page-snap.png
  src/main/java/org/mskcc/cbio/oncokb/security/uuid/TokenProvider.java
  src/main/webapp/app/components/tokenInputGroups/TokenInputGroups.tsx
  src/main/webapp/app/pages/AccountPage.tsx
  src/main/webapp/app/store/AuthenticationStore.ts
Labels: enhancement

#1076 Include 2023 year end summary && Move YES page to About page
  screenshot-test/__baseline_snapshots__/About Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Team Page without Login-snap.png
  src/main/webapp/app/components/Header.tsx
  src/main/webapp/app/pages/aboutGroup/AboutPageNavTab.tsx
  src/main/webapp/app/pages/newsPage/ChangedAnnotatonListItem.tsx
  src/main/webapp/app/pages/newsPage/NewsPage.tsx
  src/main/webapp/app/pages/newsPage/NewsPageContent.tsx
  src/main/webapp/app/pages/newsPage/NewsPageNavTab.tsx
  src/main/webapp/app/pages/yearEndSummaryPage/BiomarkerTable.tsx
  src/main/webapp/app/pages/yearEndSummaryPage/BiomarkerTableData.tsx
  src/main/webapp/app/pages/yearEndSummaryPage/YearEndSummaryPage.tsx
  src/main/webapp/app/routes/routes.tsx
  src/main/webapp/app/shared/utils/UrlUtils.tsx
  src/main/webapp/app/shared/utils/Utils.tsx
Labels: feature

#1078 Capture smartsheet exception more granularly && Add sentry service to capture exception or message
  src/main/java/org/mskcc/cbio/oncokb/service/SentryService.java
  src/main/java/org/mskcc/cbio/oncokb/service/SmartsheetService.java
Labels: enhancement

#1079 Update z-index of the sticky panel under the header
  screenshot-test/__baseline_snapshots__/About Page without Login-snap.png
  screenshot-test/__baseline_snapshots__/Alteration Page with Cancer Type - With login - Mobile-snap.png
  screenshot-test/__baseline_snapshots__/Alteration Page with Cancer Type - Without login - Mobile-snap.png
  screenshot-test/__baseline_snapshots__/Team Page without Login-snap.png
  src/main/webapp/app/layout.scss
  src/main/webapp/app/pages/aboutGroup/AboutPageNavTab.tsx
  src/main/webapp/app/pages/newsPage/NewsPageNavTab.tsx
  src/main/webapp/app/variables.scss
Labels: fix
