Repository oncokb/oncokb-public, pull requests merged in 2024-03, with the labels that each got.

#1088 Add option to delete company
  screenshot-test/__baseline_snapshots__/Company Details Page-snap.png
  src/main/java/org/mskcc/cbio/oncokb/service/impl/CompanyServiceImpl.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/CompanyResource.java
  src/main/webapp/app/pages/companyPage/CompanyPage.tsx
  src/main/webapp/app/shared/api/generated/API-docs.json
  src/main/webapp/app/shared/api/generated/API.ts
Labels: feature

#1096 Fix NCT reference link
  src/main/webapp/app/oncokb-frontend-commons/src/components/RefComponent.tsx
  src/main/webapp/app/oncokb-frontend-commons/src/lib/urls.ts
Labels: fix

#1010 Add feature to filter by date in users analysis table
  screenshot-test/App.screenshot.js
  screenshot-test/__baseline_snapshots__/Company User Details Page-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#Resource Detail-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#Resource Overview-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#User Detail-snap.png
  screenshot-test/__baseline_snapshots__/Usage Analysis Page#User Overview-snap.png
  screenshot-test/__baseline_snapshots__/User Details Page-snap.png
  screenshot-test/data/api-usage-summary-users.json
  screenshot-test/data/api-usage-users-2021.json
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisController.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/vm/usageAnalysis/UserOverviewUsage.java
  src/main/webapp/app/components/calendarButton/UsageAnalysisCalendarButton.tsx
  src/main/webapp/app/config/constants.tsx
  src/main/webapp/app/pages/usageAnalysisPage/ResourceUsageDetailsTable.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UsageAnalysisPage.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UsageAnalysisTable.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UsageToggleGroup.tsx
  src/main/webapp/app/pages/usageAnalysisPage/UserUsageDetailsTable.tsx
  src/main/webapp/app/shared/api/generated/API.ts
Labels: enhancement, Ready to merge

#1099 Fixed typo in company page
  screenshot-test/__baseline_snapshots__/Company Details Page-snap.png
  src/main/webapp/app/pages/companyPage/CompanyPage.tsx
Labels: fix
