Repository oncokb/oncokb-public, pull requests merged in 2024-07, with the labels that each got.

#1125 Limit request methods on the proxy endpoint
  src/main/java/org/mskcc/cbio/oncokb/web/rest/ApiProxy.java
Labels: enhancement

#1136 Fix FDA recognition letter linkout
  src/main/webapp/app/pages/aboutGroup/FdaRecognitionPage.tsx
Labels: fix

#1133 Added unit test to usage metrics endpoints
  src/main/java/org/mskcc/cbio/oncokb/config/ClockConfig.java
  src/main/java/org/mskcc/cbio/oncokb/config/Constants.java
  src/main/java/org/mskcc/cbio/oncokb/util/TimeUtil.java
  src/main/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisController.java
  src/test/java/org/mskcc/cbio/oncokb/web/rest/UsageAnalysisControllerIT.java
Labels: feature
